### ISSUE TITLE
ReferenceError: progression is not defined

### ISSUE THREAD

**Issue by etotman** [scribbletune/scribbletune.com#7]
https://scribbletune.com/examples/chord-progressions

const progMinor = progression('m').join(' ');
                  ^

ReferenceError: progression is not defined
    at Object.<anonymous> (/Users/node/chordprog.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

**Comment by etotman** [comment]
Fixed by changing:
`const progMinor = progression('m').join(' ');`
to
`const progMinor = scribble.progression('m').join(' ');`
